import AuthBackgroundShape from '@/features/auth/auth-background-shape';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Auth Layout',
  description: 'Generated by create next app',
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className='relative flex h-auto min-h-screen items-center justify-center overflow-x-hidden px-4 py-10 sm:px-6 lg:px-8'>
      <div className='absolute pointer-events-none'>
        <AuthBackgroundShape />
      </div>

      {children}
    </main>
  );
}
