import type { Metadata } from 'next';

import AuthBackgroundShape from '@/features/auth/components/auth-background-shape';

export const metadata: Metadata = {
  title: 'Rotate Keys - Authentication',
  description: 'Generated by create next app',
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className='relative flex justify-center items-center px-4 sm:px-6 lg:px-8 py-10 h-auto min-h-screen overflow-x-hidden'>
      <div className='absolute pointer-events-none'>
        <AuthBackgroundShape />
      </div>

      {children}
    </main>
  );
}
