import { NuqsAdapter } from 'nuqs/adapters/next/app';
import { type Metadata } from 'next';

import Footer from '@/components/shared/footer';
import Header from '@/components/shared/header';

export const metadata: Metadata = {
  title: 'Root Layout',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Header />
      <NuqsAdapter>{children}</NuqsAdapter>
      <Footer />
    </>
  );
}
