import Footer from '@/components/shared/footer';
import Header from '@/components/shared/header';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Root Layout',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Header />
      {children}
      <Footer />
    </>
  );
}
