import type { Metadata } from 'next';
import { NextIntlClientProvider } from 'next-intl';
import { Baumans, Freehand, Poppins } from 'next/font/google';

import { Toaster } from '@/components/ui/sonner';
import { TooltipProvider } from '@/components/ui/tooltip';
import { ConsentProvider } from '@/providers/consent-provider';
import { ThemeProvider } from '@/providers/theme-provider';
import { TRPCReactProvider } from '@/trpc/client';
import './globals.css';

const baumans = Baumans({
  variable: '--display-family',
  subsets: ['latin'],
  weight: ['400'],
});

const poppins = Poppins({
  variable: '--body-family',
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

const freehand = Freehand({
  variable: '--mono-family',
  subsets: ['latin'],
  weight: ['400'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function AppLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      className={`${poppins.variable} ${freehand.variable} ${baumans.variable} antialiased selection:bg-primary/50 selection:text-primary-foreground/90`}
      suppressHydrationWarning>
      <body className='font-body'>
        <NextIntlClientProvider>
          <ConsentProvider>
            <TRPCReactProvider>
              <ThemeProvider
                attribute='class'
                defaultTheme='system'
                enableSystem
                disableTransitionOnChange>
                <TooltipProvider>{children}</TooltipProvider>
                <Toaster position='top-center' richColors closeButton />
              </ThemeProvider>
            </TRPCReactProvider>
          </ConsentProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
