import type { Metadata } from 'next';
import { Baumans, Freehand, Poppins } from 'next/font/google';

import { Toaster } from '@/components/ui/sonner';
import { TooltipProvider } from '@/components/ui/tooltip';
import { ThemeProvider } from '@/providers/theme-provider';
import './globals.css';

const baumans = Baumans({
  variable: '--display-family',
  subsets: ['latin'],
  weight: ['400'],
});

const poppins = Poppins({
  variable: '--body-family',
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

const freehand = Freehand({
  variable: '--mono-family',
  subsets: ['latin'],
  weight: ['400'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function AppLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      className={`${poppins.variable} ${freehand.variable} ${baumans.variable} antialiased selection:bg-primary/50 selection:text-primary-foreground/90`}
      suppressHydrationWarning>
      <body className='font-body'>
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange>
          <TooltipProvider>{children}</TooltipProvider>
          <Toaster position='top-center' richColors closeButton />
        </ThemeProvider>
      </body>
    </html>
  );
}
